# Generated by Django 6.0.1 on 2026-01-20 16:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company Name', max_length=255)),
                ('address', models.TextField(help_text='Full company address')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('uid', models.CharField(blank=True, help_text='Umsatzsteuer-Identifikationsnummer (Austrian VAT ID)', max_length=50, verbose_name='UID')),
                ('iban', models.CharField(blank=True, help_text='IBAN for bank transfers', max_length=34)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('payment_terms', models.TextField(blank=True, help_text='Default payment terms/notes to display on invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Custom payment instructions for this invoice (overrides company default)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_label',
            field=models.CharField(choices=[('mwst', 'MwSt (Mehrwertsteuer)'), ('vat', 'VAT')], default='mwst', max_length=10, verbose_name='Tax Label'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
