# Generated by Django 6.0.1 on 2026-01-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_companyprofile_invoice_payment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
