# Generated by Django 6.0.1 on 2026-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='display_address',
            field=models.BooleanField(default=True, verbose_name='Show Address on PDF'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='display_company_name',
            field=models.BooleanField(default=True, verbose_name='Show Company Name on PDF'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='display_email',
            field=models.BooleanField(default=True, verbose_name='Show Email on PDF'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='display_logo',
            field=models.BooleanField(default=True, verbose_name='Show Logo on PDF'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='display_phone',
            field=models.BooleanField(default=True, verbose_name='Show Phone on PDF'),
        ),
    ]
