# Generated by Django 6.0.1 on 2026-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_companyprofile_display_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
            ],
            options={
                'verbose_name': 'Document Archive',
                'verbose_name_plural': 'Document Archive',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.client',),
        ),
        migrations.CreateModel(
            name='VATReport',
            fields=[
            ],
            options={
                'verbose_name': 'VAT Summary',
                'verbose_name_plural': 'VAT Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoice',),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
