# Generated by Django 6.0.1 on 2026-01-23 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_options_remove_invoice_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='mileage_base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.42'), max_digits=5, verbose_name='Mileage Base Rate (€/km)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mileage_extra_person_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5, verbose_name='Extra Person Rate (€/km)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='apply_vat',
            field=models.BooleanField(default=True, verbose_name='Apply VAT'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service / Leistung'), ('expense', 'Expense / Spesen'), ('mileage', 'Mileage / Kilometerstand')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='num_people',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of People (for Mileage)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
