# Generated by Django 6.0.1 on 2026-02-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_companyprofile_mileage_base_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='e.g. 2024', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.DecimalField(decimal_places=2, help_text='Income from this amount', max_digits=12)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Income up to this amount (leave blank for infinite)', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate in percentage (e.g. 20.00)', max_digits=5)),
                ('description', models.CharField(blank=True, help_text="Label for display, e.g. '20% (12k-20k)'", max_length=255)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='invoices.taxyear')),
            ],
            options={
                'verbose_name': 'Tax Bracket',
                'verbose_name_plural': 'Tax Brackets',
                'ordering': ['lower_limit'],
            },
        ),
    ]
