# Generated by Django 6.0.1 on 2026-02-01 12:48

import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_taxyear_taxbracket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedTax',
            fields=[
            ],
            options={
                'verbose_name': 'Estimated Tax',
                'verbose_name_plural': 'Estimated Tax',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoice',),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companyprofile',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taxbracket',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taxyear',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterField(
            model_name='taxyear',
            name='year',
            field=models.PositiveIntegerField(help_text='e.g. 2024'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='client',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='taxbracket',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='invoices.tenant'),
        ),
        migrations.AddField(
            model_name='taxyear',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to='invoices.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taxyear',
            unique_together={('tenant', 'year')},
        ),
    ]
