# Generated by Django 6.0.1 on 2026-02-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_estimatedtax_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('tenant', 'client', 'name')},
        ),
    ]
