# Generated by Django 6.0.1 on 2026-02-01 12:49

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='taxyear',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to='invoices.tenant'),
        ),
    ]
