# Generated by Django 6.0.1 on 2026-02-01 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_client_creator_invoice_creator_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='companyprofile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taxbracket',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taxyear',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='invoices.tenant'),
        ),
        migrations.AlterField(
            model_name='taxyear',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to='invoices.tenant'),
        ),
    ]
