# Generated by Django 6.0.1 on 2026-02-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_alter_client_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='uuid',
        ),
        migrations.AddField(
            model_name='client',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UID'),
        ),
    ]
