# Generated by Django 6.0.1 on 2026-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_remove_client_uuid_client_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name_extension',
            field=models.CharField(blank=True, help_text='e.g. Department, c/o, or second line', max_length=255, null=True, verbose_name='Name Extension'),
        ),
    ]
