# Generated by Django 6.0.1 on 2026-02-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_client_name_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='invoices.invoice', verbose_name='Original Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('invalid', 'Invalid')], default='draft', max_length=20),
        ),
    ]
