# Generated by Django 6.0.1 on 2026-02-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_alter_client_name_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
