# Generated by Django 6.0.1 on 2026-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_invoiceitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apply_vat',
            field=models.BooleanField(default=True, verbose_name='Apply VAT'),
        ),
    ]
